# Contratos alinhados com o backend principal do CriaByte e com os formulários
# administrativos do frontend React revisados em 25/08/2026.

SCHEMAS = {
    "PROCESSADOR": ("HARDWARE", "especificacaoProcessador", [
        "socket", "familia", "linha", "geracao", "arquitetura", "litografiaNm", "nucleos", "threads",
        "frequenciaBaseMhz", "frequenciaTurboMhz", "cacheL2Mb", "cacheL3Mb", "tdpWatts",
        "possuiVideoIntegrado", "modeloVideoIntegrado", "tiposMemoriaSuportados", "frequenciaMemoriaMaximaMhz",
        "capacidadeMemoriaMaximaGb", "canaisMemoria", "suportaEcc", "temperaturaMaximaC", "versaoPcie",
        "lanesPcie", "coolerIncluso", "multiplicadorDesbloqueado", "suporteOverclock", "dataLancamento",
    ]),
    "PLACA_MAE": ("HARDWARE", "especificacaoPlacaMae", [
        "socket", "chipset", "formato", "revisao", "biosInicial", "tiposMemoriaSuportados", "formatosMemoriaSuportados",
        "frequenciasMemoriaJedecMhz", "frequenciasMemoriaOverclockMhz", "slotsMemoria", "capacidadeMaximaMemoriaGb",
        "capacidadeMaximaPorSlotGb", "suportaXmp", "suportaExpo", "suportaEcc", "suportaMemoriaRegistrada", "saidasVideo",
        "portasSata", "versaoPcie", "wifi", "bluetooth", "ethernet", "biosFlashback", "biosMinima", "slotsM2",
    ]),
    "MEMORIA_RAM": ("HARDWARE", "especificacaoMemoriaRam", [
        "tipo", "formato", "capacidadePorModuloGb", "quantidadeModulos", "frequenciaMhz", "frequenciaJedecMhz",
        "latenciaCl", "tensaoVolts", "ecc", "registrada", "suportaXmp", "suportaExpo", "alturaMm", "rgb", "consumoWatts",
    ]),
    "PLACA_VIDEO": ("HARDWARE", "especificacaoPlacaVideo", [
        "chipset", "gpu", "arquitetura", "memoriaVideoGb", "tipoMemoriaVideo", "barramentoBits", "clockBaseMhz",
        "clockBoostMhz", "geracaoPcie", "larguraPcie", "comprimentoMm", "alturaMm", "espessuraMm", "slotsOcupados",
        "consumoWatts", "potenciaFonteRecomendadaWatts", "conectoresPcie6Pinos", "conectoresPcie8Pinos", "conectores12vhpwr",
        "conectores12v2x6", "saidasVideo", "hdmi", "displayPort",
    ]),
    "ARMAZENAMENTO": ("HARDWARE", "especificacaoArmazenamento", [
        "tipo", "formato", "interface", "capacidadeGb", "tamanhoM2Mm", "chaveM2", "geracaoPcie", "pistasPcie",
        "leituraSequencialMbps", "escritaSequencialMbps", "alturaMm", "larguraMm", "profundidadeMm", "espessuraMm",
        "consumoWatts", "possuiDissipador",
    ]),
    "FONTE": ("HARDWARE", "especificacaoFonte", [
        "formato", "potenciaWatts", "certificacao", "modularidade", "comprimentoMm", "larguraMm", "alturaMm",
        "padraoAtx", "eficienciaPercentual", "correnteLinha12vAmperes", "conectoresAtx24Pinos", "conectoresEpsCpu",
        "conectoresPcie6Pinos", "conectoresPcie8Pinos", "conectores12vhpwr", "conectores12v2x6", "conectoresSata",
        "conectoresMolex", "protecoes", "tensaoEntrada",
    ]),
    "GABINETE": ("HARDWARE", "especificacaoGabinete", [
        "tamanho", "alturaMm", "larguraMm", "profundidadeMm", "formatosPlacaMaeSuportados", "formatosFonteSuportados",
        "comprimentoMaximoFonteMm", "comprimentoMaximoGpuMm", "alturaMaximaGpuMm", "slotsMaximosGpu",
        "alturaMaximaCoolerCpuMm", "baias25", "baias35", "slotsTraseiros", "suportaGpuVertical",
        "espacoGerenciamentoCabosMm", "suportesFans", "suportesRadiador",
    ]),
    "COOLER": ("HARDWARE", "especificacaoCooler", [
        "tipo", "socketsSuportados", "capacidadeTermicaWatts", "alturaMm", "larguraMm", "profundidadeMm", "alturaLivreRamMm",
        "tamanhoRadiadorMm", "espessuraRadiadorMm", "quantidadeVentoinhas", "tamanhoVentoinhaMm", "espessuraVentoinhaMm",
        "comprimentoMangueirasMm", "conectorBomba", "consumoBombaWatts", "consumoWatts", "ruidoDb", "vidaUtilHoras",
        "pesoGramas", "velocidadeMaxRpm", "fluxoArCfm", "rgb", "argb",
    ]),
    "VENTOINHA": ("HARDWARE", "especificacaoVentoinha", [
        "tamanhoMm", "espessuraMm", "rpmMinima", "rpmMaxima", "fluxoArCfm", "pressaoEstaticaMmH2o", "ruidoDb", "conector",
        "tensaoVolts", "correnteAmperes", "pwm", "rgb", "argb", "fluxoReverso",
    ]),
    "MONITOR": ("PRODUTO", "especificacaoMonitor", [
        "tamanhoPolegadas", "resolucao", "taxaAtualizacaoHz", "tipoPainel", "tempoRespostaMs", "brilhoNits", "hdr",
        "adaptiveSync", "gSync", "freeSync", "hdmi", "displayPort", "usbC", "vesa",
    ]),
    "MOUSE": ("PRODUTO", "especificacaoMouse", [
        "sensor", "dpiMaximo", "pollingRateHz", "botoes", "pesoGramas", "conexao", "mao", "bluetooth", "wireless", "cabo", "rgb",
    ]),
    "TECLADO": ("PRODUTO", "especificacaoTeclado", [
        "tipo", "layout", "switch", "tamanho", "abnt2", "conexao", "bluetooth", "wireless", "usb", "rgb", "hotSwap",
    ]),
    # No backend real, especificacaoHeadset é aceita apenas na categoria slug
    # "headsets". A categoria comercial "fones" existe, mas não possui tabela
    # estruturada própria; por isso FONE não injeta especificacaoHeadset.
    "FONE": ("PRODUTO", None, [
        "tipoConexao", "wireless", "bluetooth", "driverMm", "microfone", "somSurround", "impedancia", "pesoGramas", "bateriaHoras",
    ]),
    "HEADSET": ("PRODUTO", "especificacaoHeadset", [
        "tipoConexao", "wireless", "bluetooth", "driverMm", "microfone", "somSurround", "impedancia", "pesoGramas", "bateriaHoras",
    ]),
    # O backend atual não possui tabela estruturada específica para estas categorias.
    # O coletor ainda identifica e extrai dados para revisão, mas não injeta campos
    # desconhecidos no payload de cadastro.
    "MICROFONE": ("PRODUTO", None, ["conexao", "padraoPolar", "taxaAmostragemKhz"]),
    "WEBCAM": ("PRODUTO", None, ["resolucao", "fps", "conexao", "microfone"]),
    "CONTROLE": ("PRODUTO", None, ["conexao", "bluetooth", "wireless", "plataformas"]),
    "CADEIRA": ("PRODUTO", None, ["material", "pesoMaximoKg", "alturaMaximaCm"]),
    "MESA": ("PRODUTO", None, ["larguraCm", "profundidadeCm", "alturaCm", "pesoMaximoKg"]),
    "MOUSEPAD": ("PRODUTO", None, ["larguraMm", "alturaMm", "espessuraMm", "rgb"]),
    "ILUMINACAO": ("PRODUTO", None, ["tipo", "rgb", "argb", "conexao"]),
    "SUPORTE_MONITOR": ("PRODUTO", None, ["quantidadeMonitores", "vesa", "pesoMaximoKg", "tamanhoMaximoPolegadas"]),
    "ORGANIZADOR_CABOS": ("PRODUTO", None, []),
    "ACESSORIO": ("PRODUTO", None, []),
    "NOTEBOOK": ("NOTEBOOK", "especificacao", [
        "processadorNome", "processadorMarca", "processadorGeracao", "nucleos", "threads", "clockBaseMhz", "clockTurboMhz", "tdpWatts",
        "gpuNome", "gpuIntegrada", "gpuDedicada", "vramGb", "tgpWatts", "ramInstaladaGb", "tipoMemoria", "frequenciaMhz",
        "ramSoldadaGb", "slotsRamTotal", "slotsRamLivres", "ramMaximaGb", "upgradeRam", "armazenamentoGb", "tipoArmazenamento",
        "slotsM2Total", "slotsM2Livres", "upgradeArmazenamento", "tamanhoTelaPolegadas", "resolucaoLargura", "resolucaoAltura",
        "taxaAtualizacaoHz", "tipoPainel", "brilhoNits", "touch", "bateriaWh", "autonomiaInformadaHoras", "potenciaCarregadorWatts",
        "pesoKg", "larguraMm", "alturaMm", "profundidadeMm", "wifi", "bluetooth", "usbA", "usbC", "thunderbolt", "hdmi",
        "displayPort", "ethernet", "leitorCartao", "sistemaOperacional", "webcam", "resolucaoWebcam", "tecladoIluminado",
        "tecladoNumerico", "leitorDigital",
    ]),
    "CELULAR": ("PRODUTO", None, [
        "processadorNome", "ramGb", "armazenamentoGb", "tamanhoTelaPolegadas", "resolucao", "taxaAtualizacaoHz", "tipoTela",
        "cameraPrincipalMp", "cameraFrontalMp", "bateriaMah", "carregamentoWatts", "cincoG", "nfc", "dualSim", "esim", "wifi",
        "bluetooth", "sistemaOperacional", "pesoGramas", "cor", "resistenciaAgua",
    ]),
    "PC_MONTADO": ("BUILD", None, ["finalidade", "resolucaoRecomendada", "componentes"]),
    "PROJETOR": ("PRODUTO", None, []),
    "CALCULADORA": ("PRODUTO", None, []),
    "TELEFONE": ("PRODUTO", None, []),
    "IMPRESSORA": ("PRODUTO", None, []),
    "SCANNER": ("PRODUTO", None, []),
    "CAIXA_DE_SOM": ("PRODUTO", None, []),
    "ROTEADOR": ("PRODUTO", None, []),
    "REPETIDOR_WIFI": ("PRODUTO", None, []),
    "SWITCH_REDE": ("PRODUTO", None, []),
    "ADAPTADOR_WIFI_BLUETOOTH": ("PRODUTO", None, []),
    "NOBREAK": ("PRODUTO", None, []),
    "ESTABILIZADOR": ("PRODUTO", None, []),
    "FILTRO_DE_LINHA": ("PRODUTO", None, []),
    "TABLET": ("PRODUTO", None, []),
    "MICROCONTROLADOR": ("PRODUTO", None, []),
    "KIT_ROBOTICA": ("PRODUTO", None, []),
    "MINI_COMPUTADOR": ("PRODUTO", None, []),
    "RELOGIO_INTELIGENTE": ("PRODUTO", None, []),
    "JOYSTICK": ("PRODUTO", None, []),
    "CONTROLE_VIDEO_GAME": ("PRODUTO", None, []),
    "VOLANTE": ("PRODUTO", None, []),
    "VIDEO_GAME": ("PRODUTO", None, []),
    "JOGO": ("PRODUTO", None, []),
    "SMART_TV": ("PRODUTO", None, []),
    "CAMERA": ("PRODUTO", None, []),
    "CARREGADOR": ("PRODUTO", None, []),
    "POWER_BANK": ("PRODUTO", None, []),
    "CABO_ADAPTADOR": ("PRODUTO", None, []),
    "HUB_USB": ("PRODUTO", None, []),
    "DOCK_STATION": ("PRODUTO", None, []),
    "PEN_DRIVE": ("PRODUTO", None, []),
    "CARTAO_MEMORIA": ("PRODUTO", None, []),
    "LEITOR_CARTAO": ("PRODUTO", None, []),
    "ARMAZENAMENTO_EXTERNO": ("PRODUTO", None, []),
    "IMPRESSORA_3D": ("PRODUTO", None, []),
    "ACESSORIO_IMPRESSAO_3D": ("PRODUTO", None, []),
}

REQUIRED = {
    "PROCESSADOR": ["socket", "tiposMemoriaSuportados"],
    "PLACA_MAE": ["socket", "chipset", "formato", "tiposMemoriaSuportados", "slotsMemoria"],
    "MEMORIA_RAM": ["tipo", "formato", "capacidadePorModuloGb", "quantidadeModulos", "frequenciaMhz"],
    "PLACA_VIDEO": ["comprimentoMm"],
    "ARMAZENAMENTO": ["tipo", "formato", "interface", "capacidadeGb"],
    "FONTE": ["formato", "potenciaWatts"],
    "GABINETE": ["tamanho", "alturaMm", "larguraMm", "profundidadeMm", "formatosPlacaMaeSuportados", "formatosFonteSuportados"],
    "COOLER": ["tipo", "socketsSuportados"],
    "VENTOINHA": ["tamanhoMm", "conector"],
}

HARDWARE_CATEGORIES = {
    "PROCESSADOR", "PLACA_MAE", "MEMORIA_RAM", "PLACA_VIDEO", "ARMAZENAMENTO",
    "FONTE", "GABINETE", "COOLER", "VENTOINHA",
}

FRONTEND_ONLY_GENERIC_CATEGORIES = {
    "WEBCAM", "CONTROLE", "CADEIRA", "MESA", "MOUSEPAD", "ILUMINACAO", "SUPORTE_MONITOR",
    "ORGANIZADOR_CABOS", "ACESSORIO",
}

CATEGORY_SLUGS = {
    "PC_MONTADO": "pcs-montados",
    "NOTEBOOK": "notebooks",
    "PROCESSADOR": "processadores",
    "COOLER": "coolers",
    "PLACA_MAE": "placas-mae",
    "MEMORIA_RAM": "memorias-ram",
    "PLACA_VIDEO": "placas-video",
    "ARMAZENAMENTO": "armazenamento",
    "FONTE": "fontes",
    "GABINETE": "gabinetes",
    "VENTOINHA": "ventoinhas",
    "MONITOR": "monitores",
    "MOUSE": "mouses",
    "TECLADO": "teclados",
    "HEADSET": "headsets",
    "FONE": "fones",
    "MICROFONE": "microfones",
    "WEBCAM": "webcams",
    "CONTROLE": "controles",
    "MOUSEPAD": "mousepads",
    "CADEIRA": "cadeiras",
    "MESA": "mesas",
    "SUPORTE_MONITOR": "suportes-monitor",
    "ILUMINACAO": "iluminacao",
    "ORGANIZADOR_CABOS": "organizadores-cabos",
    "ACESSORIO": "acessorios",
    "CELULAR": "celulares",
    "PROJETOR": "projetores",
    "CALCULADORA": "calculadoras",
    "TELEFONE": "telefones",
    "IMPRESSORA": "impressoras",
    "SCANNER": "scanners",
    "CAIXA_DE_SOM": "caixas-de-som",
    "ROTEADOR": "roteadores",
    "REPETIDOR_WIFI": "repetidores-wifi",
    "SWITCH_REDE": "switches-de-rede",
    "ADAPTADOR_WIFI_BLUETOOTH": "adaptadores-wifi-bluetooth",
    "NOBREAK": "nobreaks",
    "ESTABILIZADOR": "estabilizadores",
    "FILTRO_DE_LINHA": "filtros-de-linha",
    "TABLET": "tablets",
    "MICROCONTROLADOR": "microcontroladores",
    "KIT_ROBOTICA": "kits-arduino-robotica",
    "MINI_COMPUTADOR": "mini-computadores",
    "RELOGIO_INTELIGENTE": "relogios-inteligentes",
    "JOYSTICK": "joysticks",
    "CONTROLE_VIDEO_GAME": "controles-videogame",
    "VOLANTE": "volantes",
    "VIDEO_GAME": "videogames-consoles",
    "JOGO": "jogos",
    "SMART_TV": "smart-tvs",
    "CAMERA": "cameras",
    "CARREGADOR": "carregadores",
    "POWER_BANK": "power-banks",
    "CABO_ADAPTADOR": "cabos-adaptadores",
    "HUB_USB": "hubs-usb",
    "DOCK_STATION": "dock-stations",
    "PEN_DRIVE": "pen-drives",
    "CARTAO_MEMORIA": "cartoes-de-memoria",
    "LEITOR_CARTAO": "leitores-de-cartao",
    "ARMAZENAMENTO_EXTERNO": "armazenamento-externo",
    "IMPRESSORA_3D": "impressoras-3d",
    "ACESSORIO_IMPRESSAO_3D": "acessorios-impressao-3d",
}
